//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCCodeCopAnalyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BCCodeCopAnalyzer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BCCodeCopAnalyzer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BCCodeCopAnalyzer.BCCodeCopAnalyzer", typeof(BCCodeCopAnalyzer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BC.
        /// </summary>
        internal static string AnalyzerPrefix {
            get {
                return ResourceManager.GetString("AnalyzerPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable name should not contain whitespace.
        /// </summary>
        internal static string Rule0001VariableNameShouldNotContainWhiteSpaceDescription {
            get {
                return ResourceManager.GetString("Rule0001VariableNameShouldNotContainWhiteSpaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be used as a variable name. Names may not contain whitespace..
        /// </summary>
        internal static string Rule0001VariableNameShouldNotContainWhiteSpaceFormat {
            get {
                return ResourceManager.GetString("Rule0001VariableNameShouldNotContainWhiteSpaceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable name should not contain whitespace.
        /// </summary>
        internal static string Rule0001VariableNameShouldNotContainWhiteSpaceTitle {
            get {
                return ResourceManager.GetString("Rule0001VariableNameShouldNotContainWhiteSpaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable name should not contain wildcard symbols such as % or &amp;.
        /// </summary>
        internal static string Rule0002VariableShouldNotContainWildcardSymbolsDescription {
            get {
                return ResourceManager.GetString("Rule0002VariableShouldNotContainWildcardSymbolsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be used as a variable name. Names should not contain wildcard symbols such as % or &amp;..
        /// </summary>
        internal static string Rule0002VariableShouldNotContainWildcardSymbolsFormat {
            get {
                return ResourceManager.GetString("Rule0002VariableShouldNotContainWildcardSymbolsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable name should not contain wildcard symbols such as % or &amp;.
        /// </summary>
        internal static string Rule0002VariableShouldNotContainWildcardSymbolsTitle {
            get {
                return ResourceManager.GetString("Rule0002VariableShouldNotContainWildcardSymbolsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure name should not contain whitespace.
        /// </summary>
        internal static string Rule0003MethodsNameShouldNotContainWhiteSpaceDescription {
            get {
                return ResourceManager.GetString("Rule0003MethodsNameShouldNotContainWhiteSpaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be used as a procedure name. Procedure name should not contain whitespace..
        /// </summary>
        internal static string Rule0003MethodsNameShouldNotContainWhiteSpaceFormat {
            get {
                return ResourceManager.GetString("Rule0003MethodsNameShouldNotContainWhiteSpaceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure name should not contain whitespace.
        /// </summary>
        internal static string Rule0003MethodsNameShouldNotContainWhiteSpaceTitle {
            get {
                return ResourceManager.GetString("Rule0003MethodsNameShouldNotContainWhiteSpaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global variables section should be above triggers and procedures.
        /// </summary>
        internal static string Rule0004GlobalVariablesMayBeAboveTriggersProceduresDescription {
            get {
                return ResourceManager.GetString("Rule0004GlobalVariablesMayBeAboveTriggersProceduresDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move global variables section, it may be above triggers and procedures..
        /// </summary>
        internal static string Rule0004GlobalVariablesMayBeAboveTriggersProceduresFormat {
            get {
                return ResourceManager.GetString("Rule0004GlobalVariablesMayBeAboveTriggersProceduresFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global variables section should be above triggers and procedures.
        /// </summary>
        internal static string Rule0004GlobalVariablesMayBeAboveTriggersProceduresTitle {
            get {
                return ResourceManager.GetString("Rule0004GlobalVariablesMayBeAboveTriggersProceduresTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects which type is: Table, Page, XmlPort, Report, Query must have caption property.
        /// </summary>
        internal static string Rule0005ObjectsMustHaveCaptionPropertyDescription {
            get {
                return ResourceManager.GetString("Rule0005ObjectsMustHaveCaptionPropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;, must have caption property. Objects which type is: Table, Page, XmlPort, Report, Query must have captions..
        /// </summary>
        internal static string Rule0005ObjectsMustHaveCaptionPropertyFormat {
            get {
                return ResourceManager.GetString("Rule0005ObjectsMustHaveCaptionPropertyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects which type is: Table, Page, XmlPort, Report, Query must have caption property.
        /// </summary>
        internal static string Rule0005ObjectsMustHaveCaptionPropertyTitle {
            get {
                return ResourceManager.GetString("Rule0005ObjectsMustHaveCaptionPropertyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Fields must have caption property.
        /// </summary>
        internal static string Rule0006TableFieldsMustHaveCaptionPropertyDescription {
            get {
                return ResourceManager.GetString("Rule0006TableFieldsMustHaveCaptionPropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;, may have caption property. Table Fields must have caption property..
        /// </summary>
        internal static string Rule0006TableFieldsMustHaveCaptionPropertyFormat {
            get {
                return ResourceManager.GetString("Rule0006TableFieldsMustHaveCaptionPropertyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Fields must have caption property.
        /// </summary>
        internal static string Rule0006TableFieldsMustHaveCaptionPropertyTitle {
            get {
                return ResourceManager.GetString("Rule0006TableFieldsMustHaveCaptionPropertyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum Value must have caption property.
        /// </summary>
        internal static string Rule0007EnumValuesMustHaveCaptionPropertyDescription {
            get {
                return ResourceManager.GetString("Rule0007EnumValuesMustHaveCaptionPropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;, may have caption property. Enum Value must have caption property..
        /// </summary>
        internal static string Rule0007EnumValuesMustHaveCaptionPropertyFormat {
            get {
                return ResourceManager.GetString("Rule0007EnumValuesMustHaveCaptionPropertyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum Value must have caption property.
        /// </summary>
        internal static string Rule0007EnumValuesMustHaveCaptionPropertyTitle {
            get {
                return ResourceManager.GetString("Rule0007EnumValuesMustHaveCaptionPropertyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page parts: Request Page, Page Group, Page Part, Page Action, Page Action Group must have caption property.
        /// </summary>
        internal static string Rule0008PagePartsMustHaveCaptionPropertyDescription {
            get {
                return ResourceManager.GetString("Rule0008PagePartsMustHaveCaptionPropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;, must have caption property. Page parts: Page Group, Page Part, Page Action, Page Action Group must have caption property..
        /// </summary>
        internal static string Rule0008PagePartsMustHaveCaptionPropertyFormat {
            get {
                return ResourceManager.GetString("Rule0008PagePartsMustHaveCaptionPropertyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page parts: Request Page, Page Group, Page Part, Page Action, Page Action Group must have caption property.
        /// </summary>
        internal static string Rule0008PagePartsMustHaveCaptionPropertyTitle {
            get {
                return ResourceManager.GetString("Rule0008PagePartsMustHaveCaptionPropertyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First 19 Field IDs are reserved to primary key fields.
        /// </summary>
        internal static string Rule0009First19TableFieldsIDReservedToPrimaryKeyDescription {
            get {
                return ResourceManager.GetString("Rule0009First19TableFieldsIDReservedToPrimaryKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber &apos;{0}&apos; field. First 19 Field IDs are reserved to primary key fields..
        /// </summary>
        internal static string Rule0009First19TableFieldsIDReservedToPrimaryKeyFormat {
            get {
                return ResourceManager.GetString("Rule0009First19TableFieldsIDReservedToPrimaryKeyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First 19 Field IDs are reserved to primary key fields.
        /// </summary>
        internal static string Rule0009First19TableFieldsIDReservedToPrimaryKeyTitle {
            get {
                return ResourceManager.GetString("Rule0009First19TableFieldsIDReservedToPrimaryKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All values in enum extensions should be numbered in the dedicated extension or PTE range.
        /// </summary>
        internal static string Rule0011EnumExtensionsValuesNumberedInDedicatedRangeDescription {
            get {
                return ResourceManager.GetString("Rule0011EnumExtensionsValuesNumberedInDedicatedRangeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber &apos;{0}&apos; value. All values in enum extensions should be numbered in the dedicated extension or PTE range..
        /// </summary>
        internal static string Rule0011EnumExtensionsValuesNumberedInDedicatedRangeFormat {
            get {
                return ResourceManager.GetString("Rule0011EnumExtensionsValuesNumberedInDedicatedRangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All values in enum extensions should be numbered in the dedicated extension or PTE range.
        /// </summary>
        internal static string Rule0011EnumExtensionsValuesNumberedInDedicatedRangeTitle {
            get {
                return ResourceManager.GetString("Rule0011EnumExtensionsValuesNumberedInDedicatedRangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Actions sections should be removed.
        /// </summary>
        internal static string Rule0012EmptyActionsSectionDescription {
            get {
                return ResourceManager.GetString("Rule0012EmptyActionsSectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove empty Actions section..
        /// </summary>
        internal static string Rule0012EmptyActionsSectionFormat {
            get {
                return ResourceManager.GetString("Rule0012EmptyActionsSectionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Actions sections should be removed.
        /// </summary>
        internal static string Rule0012EmptyActionsSectionTitle {
            get {
                return ResourceManager.GetString("Rule0012EmptyActionsSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty OnRun triggers should be removed.
        /// </summary>
        internal static string Rule0013EmptyOnRunTriggerDescription {
            get {
                return ResourceManager.GetString("Rule0013EmptyOnRunTriggerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove empty OnRun trigger..
        /// </summary>
        internal static string Rule0013EmptyOnRunTriggerFormat {
            get {
                return ResourceManager.GetString("Rule0013EmptyOnRunTriggerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty OnRun triggers should be removed.
        /// </summary>
        internal static string Rule0013EmptyOnRunTriggerTitle {
            get {
                return ResourceManager.GetString("Rule0013EmptyOnRunTriggerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardcoding IP addresses is security-sensitive.
        /// </summary>
        internal static string Rule0014HardcodedIpAddressDescription {
            get {
                return ResourceManager.GetString("Rule0014HardcodedIpAddressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure using hardcoded IP address &apos;{0}&apos; is safe..
        /// </summary>
        internal static string Rule0014HardcodedIpAddressFormat {
            get {
                return ResourceManager.GetString("Rule0014HardcodedIpAddressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardcoding IP addresses is security-sensitive.
        /// </summary>
        internal static string Rule0014HardcodedIpAddressTitle {
            get {
                return ResourceManager.GetString("Rule0014HardcodedIpAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowFields should not be editable..
        /// </summary>
        internal static string Rule0015FlowFieldsShouldNotBeEditableDescription {
            get {
                return ResourceManager.GetString("Rule0015FlowFieldsShouldNotBeEditableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field with name &apos;{0}&apos; must have the Editable property equals false..
        /// </summary>
        internal static string Rule0015FlowFieldsShouldNotBeEditableFormat {
            get {
                return ResourceManager.GetString("Rule0015FlowFieldsShouldNotBeEditableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowFields should not be editable..
        /// </summary>
        internal static string Rule0015FlowFieldsShouldNotBeEditableTitle {
            get {
                return ResourceManager.GetString("Rule0015FlowFieldsShouldNotBeEditableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit() must have a comment to justify its existance. Either a leading or a trailing comment..
        /// </summary>
        internal static string Rule0016CommitMustBeExplainedByCommentDescription {
            get {
                return ResourceManager.GetString("Rule0016CommitMustBeExplainedByCommentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit() must have a comment to justify its existance. Either a leading or a trailing comment..
        /// </summary>
        internal static string Rule0016CommitMustBeExplainedByCommentFormat {
            get {
                return ResourceManager.GetString("Rule0016CommitMustBeExplainedByCommentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit() must have a comment to justify its existance. Either a leading or a trailing comment..
        /// </summary>
        internal static string Rule0016CommitMustBeExplainedByCommentTitle {
            get {
                return ResourceManager.GetString("Rule0016CommitMustBeExplainedByCommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using hardcoded IDs in functions is not allowed..
        /// </summary>
        internal static string Rule0017DoNotUseObjectIdInSystemFunctionsDescription {
            get {
                return ResourceManager.GetString("Rule0017DoNotUseObjectIdInSystemFunctionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using hardcoded IDs in functions is not allowed..
        /// </summary>
        internal static string Rule0017DoNotUseObjectIdInSystemFunctionsFormat {
            get {
                return ResourceManager.GetString("Rule0017DoNotUseObjectIdInSystemFunctionsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using hardcoded IDs in functions is not allowed..
        /// </summary>
        internal static string Rule0017DoNotUseObjectIdInSystemFunctionsTitle {
            get {
                return ResourceManager.GetString("Rule0017DoNotUseObjectIdInSystemFunctionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption is missing.
        /// </summary>
        internal static string Rule0018CheckForMissingCaptionsDescription {
            get {
                return ResourceManager.GetString("Rule0018CheckForMissingCaptionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must have caption property..
        /// </summary>
        internal static string Rule0018CheckForMissingCaptionsFormat {
            get {
                return ResourceManager.GetString("Rule0018CheckForMissingCaptionsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption is missing.
        /// </summary>
        internal static string Rule0018CheckForMissingCaptionsTitle {
            get {
                return ResourceManager.GetString("Rule0018CheckForMissingCaptionsTitle", resourceCulture);
            }
        }
    }
}
