//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCCodeCopAnalyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BCCodeCopAnalyzer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BCCodeCopAnalyzer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BCCodeCopAnalyzer.BCCodeCopAnalyzer", typeof(BCCodeCopAnalyzer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CM.
        /// </summary>
        internal static string AnalyzerPrefix {
            get {
                return ResourceManager.GetString("AnalyzerPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable name should not contain whitespace.
        /// </summary>
        internal static string Rule0001VariableNameShouldNotContainWhiteSpaceDescription {
            get {
                return ResourceManager.GetString("Rule0001VariableNameShouldNotContainWhiteSpaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable with name &apos;{0}&apos; must not contain whitespaces..
        /// </summary>
        internal static string Rule0001VariableNameShouldNotContainWhiteSpaceFormat {
            get {
                return ResourceManager.GetString("Rule0001VariableNameShouldNotContainWhiteSpaceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable name should not contain whitespace.
        /// </summary>
        internal static string Rule0001VariableNameShouldNotContainWhiteSpaceTitle {
            get {
                return ResourceManager.GetString("Rule0001VariableNameShouldNotContainWhiteSpaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable name should not contain wildcard symbols such as % or &amp;.
        /// </summary>
        internal static string Rule0002VariableShouldNotContainWildcardSymbolsDescription {
            get {
                return ResourceManager.GetString("Rule0002VariableShouldNotContainWildcardSymbolsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable with name &apos;{0}&apos; must not contain wildcard symbols..
        /// </summary>
        internal static string Rule0002VariableShouldNotContainWildcardSymbolsFormat {
            get {
                return ResourceManager.GetString("Rule0002VariableShouldNotContainWildcardSymbolsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable name should not contain wildcard symbols such as % or &amp;.
        /// </summary>
        internal static string Rule0002VariableShouldNotContainWildcardSymbolsTitle {
            get {
                return ResourceManager.GetString("Rule0002VariableShouldNotContainWildcardSymbolsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure name should not contain whitespace.
        /// </summary>
        internal static string Rule0003MethodsNameShouldNotContainWhiteSpaceDescription {
            get {
                return ResourceManager.GetString("Rule0003MethodsNameShouldNotContainWhiteSpaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure with name &apos;{0}&apos; must not contain whitespaces..
        /// </summary>
        internal static string Rule0003MethodsNameShouldNotContainWhiteSpaceFormat {
            get {
                return ResourceManager.GetString("Rule0003MethodsNameShouldNotContainWhiteSpaceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure name should not contain whitespace.
        /// </summary>
        internal static string Rule0003MethodsNameShouldNotContainWhiteSpaceTitle {
            get {
                return ResourceManager.GetString("Rule0003MethodsNameShouldNotContainWhiteSpaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global variables section should be above triggers and procedures.
        /// </summary>
        internal static string Rule0004GlobalVariablesMayBeAboveTriggersProceduresDescription {
            get {
                return ResourceManager.GetString("Rule0004GlobalVariablesMayBeAboveTriggersProceduresDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move global variables section, it may be above triggers and procedures..
        /// </summary>
        internal static string Rule0004GlobalVariablesMayBeAboveTriggersProceduresFormat {
            get {
                return ResourceManager.GetString("Rule0004GlobalVariablesMayBeAboveTriggersProceduresFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global variables section should be above triggers and procedures.
        /// </summary>
        internal static string Rule0004GlobalVariablesMayBeAboveTriggersProceduresTitle {
            get {
                return ResourceManager.GetString("Rule0004GlobalVariablesMayBeAboveTriggersProceduresTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First 19 Field IDs are reserved to primary key fields.
        /// </summary>
        internal static string Rule0009First19TableFieldsIDReservedToPrimaryKeyDescription {
            get {
                return ResourceManager.GetString("Rule0009First19TableFieldsIDReservedToPrimaryKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field identifier &apos;{0}&apos; is not valid. First 19 Field IDs are reserved to primary key fields..
        /// </summary>
        internal static string Rule0009First19TableFieldsIDReservedToPrimaryKeyFormat {
            get {
                return ResourceManager.GetString("Rule0009First19TableFieldsIDReservedToPrimaryKeyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First 19 Field IDs are reserved to primary key fields.
        /// </summary>
        internal static string Rule0009First19TableFieldsIDReservedToPrimaryKeyTitle {
            get {
                return ResourceManager.GetString("Rule0009First19TableFieldsIDReservedToPrimaryKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All values in enum extensions should be numbered in the dedicated extension or PTE range.
        /// </summary>
        internal static string Rule0011EnumExtensionsValuesNumberedInDedicatedRangeDescription {
            get {
                return ResourceManager.GetString("Rule0011EnumExtensionsValuesNumberedInDedicatedRangeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then enum identifier &apos;{0}&apos; is not valid. It must be withing the range &apos;{1}..
        /// </summary>
        internal static string Rule0011EnumExtensionsValuesNumberedInDedicatedRangeFormat {
            get {
                return ResourceManager.GetString("Rule0011EnumExtensionsValuesNumberedInDedicatedRangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All values in enum extensions should be numbered in the dedicated extension or PTE range.
        /// </summary>
        internal static string Rule0011EnumExtensionsValuesNumberedInDedicatedRangeTitle {
            get {
                return ResourceManager.GetString("Rule0011EnumExtensionsValuesNumberedInDedicatedRangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty OnRun triggers should be removed.
        /// </summary>
        internal static string Rule0013CheckEmptyOnRunTriggersDescription {
            get {
                return ResourceManager.GetString("Rule0013CheckEmptyOnRunTriggersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember to specify either the &apos;OnRun&apos; trigger or remove it..
        /// </summary>
        internal static string Rule0013CheckEmptyOnRunTriggersFormat {
            get {
                return ResourceManager.GetString("Rule0013CheckEmptyOnRunTriggersFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty OnRun triggers should be removed.
        /// </summary>
        internal static string Rule0013CheckEmptyOnRunTriggersTitle {
            get {
                return ResourceManager.GetString("Rule0013CheckEmptyOnRunTriggersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardcoding IP addresses is security-sensitive.
        /// </summary>
        internal static string Rule0014HardcodedIpAddressDescription {
            get {
                return ResourceManager.GetString("Rule0014HardcodedIpAddressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Label {0} must not contain IP addresses..
        /// </summary>
        internal static string Rule0014HardcodedIpAddressFormat {
            get {
                return ResourceManager.GetString("Rule0014HardcodedIpAddressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardcoding IP addresses is security-sensitive.
        /// </summary>
        internal static string Rule0014HardcodedIpAddressTitle {
            get {
                return ResourceManager.GetString("Rule0014HardcodedIpAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowFields should not be editable..
        /// </summary>
        internal static string Rule0015FlowFieldsShouldNotBeEditableDescription {
            get {
                return ResourceManager.GetString("Rule0015FlowFieldsShouldNotBeEditableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field with name &apos;{0}&apos; must have the Editable property equals false..
        /// </summary>
        internal static string Rule0015FlowFieldsShouldNotBeEditableFormat {
            get {
                return ResourceManager.GetString("Rule0015FlowFieldsShouldNotBeEditableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowFields should not be editable..
        /// </summary>
        internal static string Rule0015FlowFieldsShouldNotBeEditableTitle {
            get {
                return ResourceManager.GetString("Rule0015FlowFieldsShouldNotBeEditableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit() must have a comment to justify its existance. Either a leading or a trailing comment..
        /// </summary>
        internal static string Rule0016CommitMustBeExplainedByCommentDescription {
            get {
                return ResourceManager.GetString("Rule0016CommitMustBeExplainedByCommentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit() must have a comment to justify its existance. Either a leading or a trailing comment..
        /// </summary>
        internal static string Rule0016CommitMustBeExplainedByCommentFormat {
            get {
                return ResourceManager.GetString("Rule0016CommitMustBeExplainedByCommentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit() must have a comment to justify its existance. Either a leading or a trailing comment..
        /// </summary>
        internal static string Rule0016CommitMustBeExplainedByCommentTitle {
            get {
                return ResourceManager.GetString("Rule0016CommitMustBeExplainedByCommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using hardcoded IDs in functions is not allowed..
        /// </summary>
        internal static string Rule0017DoNotUseObjectIdInSystemFunctionsDescription {
            get {
                return ResourceManager.GetString("Rule0017DoNotUseObjectIdInSystemFunctionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using hardcoded IDs in functions is not allowed..
        /// </summary>
        internal static string Rule0017DoNotUseObjectIdInSystemFunctionsFormat {
            get {
                return ResourceManager.GetString("Rule0017DoNotUseObjectIdInSystemFunctionsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using hardcoded IDs in functions is not allowed..
        /// </summary>
        internal static string Rule0017DoNotUseObjectIdInSystemFunctionsTitle {
            get {
                return ResourceManager.GetString("Rule0017DoNotUseObjectIdInSystemFunctionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption is missing.
        /// </summary>
        internal static string Rule0018CheckForMissingCaptionsDescription {
            get {
                return ResourceManager.GetString("Rule0018CheckForMissingCaptionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must have caption property..
        /// </summary>
        internal static string Rule0018CheckForMissingCaptionsFormat {
            get {
                return ResourceManager.GetString("Rule0018CheckForMissingCaptionsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption is missing.
        /// </summary>
        internal static string Rule0018CheckForMissingCaptionsTitle {
            get {
                return ResourceManager.GetString("Rule0018CheckForMissingCaptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure must not end with semicolon..
        /// </summary>
        internal static string Rule0019SemicolonAfterProcedureDeclarationDescription {
            get {
                return ResourceManager.GetString("Rule0019SemicolonAfterProcedureDeclarationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure must not end with semicolon..
        /// </summary>
        internal static string Rule0019SemicolonAfterProcedureDeclarationFormat {
            get {
                return ResourceManager.GetString("Rule0019SemicolonAfterProcedureDeclarationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure must not end with semicolon..
        /// </summary>
        internal static string Rule0019SemicolonAfterProcedureDeclarationTitle {
            get {
                return ResourceManager.GetString("Rule0019SemicolonAfterProcedureDeclarationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedures must be either local or internal..
        /// </summary>
        internal static string Rule0020InternalProceduresDescription {
            get {
                return ResourceManager.GetString("Rule0020InternalProceduresDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedures must be either local or internal..
        /// </summary>
        internal static string Rule0020InternalProceduresFormat {
            get {
                return ResourceManager.GetString("Rule0020InternalProceduresFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedures must be either local or internal..
        /// </summary>
        internal static string Rule0020InternalProceduresTitle {
            get {
                return ResourceManager.GetString("Rule0020InternalProceduresTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolTips must end with a dot..
        /// </summary>
        internal static string Rule0021ToolTipPunctuationDescription {
            get {
                return ResourceManager.GetString("Rule0021ToolTipPunctuationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolTips must end with a dot..
        /// </summary>
        internal static string Rule0021ToolTipPunctuationFormat {
            get {
                return ResourceManager.GetString("Rule0021ToolTipPunctuationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolTips must end with a dot..
        /// </summary>
        internal static string Rule0021ToolTipPunctuationTitle {
            get {
                return ResourceManager.GetString("Rule0021ToolTipPunctuationTitle", resourceCulture);
            }
        }
    }
}
