//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanialCopAnalyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CompanialCopAnalyzer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompanialCopAnalyzer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CompanialCopAnalyzer.CompanialCopAnalyzer", typeof(CompanialCopAnalyzer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CM.
        /// </summary>
        internal static string AnalyzerPrefix {
            get {
                return ResourceManager.GetString("AnalyzerPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name for primary key must be PK..
        /// </summary>
        internal static string Rule0001KeyNamingDescription {
            get {
                return ResourceManager.GetString("Rule0001KeyNamingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key &apos;{0}&apos; has an incorrect name. The valid name is PK..
        /// </summary>
        internal static string Rule0001KeyNamingFormat {
            get {
                return ResourceManager.GetString("Rule0001KeyNamingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name for primary key must be PK..
        /// </summary>
        internal static string Rule0001KeyNamingTitle {
            get {
                return ResourceManager.GetString("Rule0001KeyNamingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable with suffix Tok must be locked..
        /// </summary>
        internal static string Rule0002LockedVariableLablesDescription {
            get {
                return ResourceManager.GetString("Rule0002LockedVariableLablesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable with suffix Tok must be locked..
        /// </summary>
        internal static string Rule0002LockedVariableLablesFormat {
            get {
                return ResourceManager.GetString("Rule0002LockedVariableLablesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable with suffix Tok must be locked..
        /// </summary>
        internal static string Rule0002LockedVariableLablesTitle {
            get {
                return ResourceManager.GetString("Rule0002LockedVariableLablesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked variables must have suffix Tok..
        /// </summary>
        internal static string Rule0002LockedVariableTokLablesDescription {
            get {
                return ResourceManager.GetString("Rule0002LockedVariableTokLablesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked variable with name &apos;{0}&apos; must have a suffix Tok..
        /// </summary>
        internal static string Rule0002LockedVariableTokLablesFormat {
            get {
                return ResourceManager.GetString("Rule0002LockedVariableTokLablesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked variables must have suffix Tok..
        /// </summary>
        internal static string Rule0002LockedVariableTokLablesTitle {
            get {
                return ResourceManager.GetString("Rule0002LockedVariableTokLablesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure name must not contain whitespaces..
        /// </summary>
        internal static string Rule0003MethodsNameShouldNotContainWhiteSpaceDescription {
            get {
                return ResourceManager.GetString("Rule0003MethodsNameShouldNotContainWhiteSpaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure with name &apos;{0}&apos; must not contain whitespaces..
        /// </summary>
        internal static string Rule0003MethodsNameShouldNotContainWhiteSpaceFormat {
            get {
                return ResourceManager.GetString("Rule0003MethodsNameShouldNotContainWhiteSpaceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure name must not contain whitespaces..
        /// </summary>
        internal static string Rule0003MethodsNameShouldNotContainWhiteSpaceTitle {
            get {
                return ResourceManager.GetString("Rule0003MethodsNameShouldNotContainWhiteSpaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First 19 field IDs are reserved for primary key fields..
        /// </summary>
        internal static string Rule0004First19TableFieldsIDReservedToPrimaryKeyDescription {
            get {
                return ResourceManager.GetString("Rule0004First19TableFieldsIDReservedToPrimaryKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field identifier &apos;{0}&apos; is not valid. First 19 Field IDs are reserved for primary key fields..
        /// </summary>
        internal static string Rule0004First19TableFieldsIDReservedToPrimaryKeyFormat {
            get {
                return ResourceManager.GetString("Rule0004First19TableFieldsIDReservedToPrimaryKeyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First 19 field IDs are reserved for primary key fields..
        /// </summary>
        internal static string Rule0004First19TableFieldsIDReservedToPrimaryKeyTitle {
            get {
                return ResourceManager.GetString("Rule0004First19TableFieldsIDReservedToPrimaryKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enum identifier must be within the allowed range..
        /// </summary>
        internal static string Rule0005EnumExtensionsValuesNumberedInDedicatedRangeDescription {
            get {
                return ResourceManager.GetString("Rule0005EnumExtensionsValuesNumberedInDedicatedRangeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Then enum identifier &apos;{0}&apos; is not valid. It must be within the range &apos;{1}..
        /// </summary>
        internal static string Rule0005EnumExtensionsValuesNumberedInDedicatedRangeFormat {
            get {
                return ResourceManager.GetString("Rule0005EnumExtensionsValuesNumberedInDedicatedRangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enum identifier must be within the allowed range..
        /// </summary>
        internal static string Rule0005EnumExtensionsValuesNumberedInDedicatedRangeTitle {
            get {
                return ResourceManager.GetString("Rule0005EnumExtensionsValuesNumberedInDedicatedRangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address must not be present in any part of the source code..
        /// </summary>
        internal static string Rule0006HardcodedIpAddressDescription {
            get {
                return ResourceManager.GetString("Rule0006HardcodedIpAddressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Label {0} must not contain IP addresses..
        /// </summary>
        internal static string Rule0006HardcodedIpAddressFormat {
            get {
                return ResourceManager.GetString("Rule0006HardcodedIpAddressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address must not be present in any part of the source code..
        /// </summary>
        internal static string Rule0006HardcodedIpAddressTitle {
            get {
                return ResourceManager.GetString("Rule0006HardcodedIpAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowFields must not be editable..
        /// </summary>
        internal static string Rule0007FlowFieldsShouldNotBeEditableDescription {
            get {
                return ResourceManager.GetString("Rule0007FlowFieldsShouldNotBeEditableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field with name &apos;{0}&apos; must have the Editable property equals false..
        /// </summary>
        internal static string Rule0007FlowFieldsShouldNotBeEditableFormat {
            get {
                return ResourceManager.GetString("Rule0007FlowFieldsShouldNotBeEditableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowFields must not be editable..
        /// </summary>
        internal static string Rule0007FlowFieldsShouldNotBeEditableTitle {
            get {
                return ResourceManager.GetString("Rule0007FlowFieldsShouldNotBeEditableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit() must have a comment to justify its existence. Either a leading or a trailing comment..
        /// </summary>
        internal static string Rule0008CommitMustBeExplainedByCommentDescription {
            get {
                return ResourceManager.GetString("Rule0008CommitMustBeExplainedByCommentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit() must have a comment to justify its existence. Either a leading or a trailing comment..
        /// </summary>
        internal static string Rule0008CommitMustBeExplainedByCommentFormat {
            get {
                return ResourceManager.GetString("Rule0008CommitMustBeExplainedByCommentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit() must have a comment to justify its existence. Either a leading or a trailing comment..
        /// </summary>
        internal static string Rule0008CommitMustBeExplainedByCommentTitle {
            get {
                return ResourceManager.GetString("Rule0008CommitMustBeExplainedByCommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using hardcoded IDs in functions is not allowed..
        /// </summary>
        internal static string Rule0009DoNotUseObjectIdInSystemFunctionsDescription {
            get {
                return ResourceManager.GetString("Rule0009DoNotUseObjectIdInSystemFunctionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using hardcoded IDs in functions is not allowed..
        /// </summary>
        internal static string Rule0009DoNotUseObjectIdInSystemFunctionsFormat {
            get {
                return ResourceManager.GetString("Rule0009DoNotUseObjectIdInSystemFunctionsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using hardcoded IDs in functions is not allowed..
        /// </summary>
        internal static string Rule0009DoNotUseObjectIdInSystemFunctionsTitle {
            get {
                return ResourceManager.GetString("Rule0009DoNotUseObjectIdInSystemFunctionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption is missing.
        /// </summary>
        internal static string Rule0010CheckForMissingCaptionsDescription {
            get {
                return ResourceManager.GetString("Rule0010CheckForMissingCaptionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must have caption property..
        /// </summary>
        internal static string Rule0010CheckForMissingCaptionsFormat {
            get {
                return ResourceManager.GetString("Rule0010CheckForMissingCaptionsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption is missing.
        /// </summary>
        internal static string Rule0010CheckForMissingCaptionsTitle {
            get {
                return ResourceManager.GetString("Rule0010CheckForMissingCaptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure must not end with semicolon..
        /// </summary>
        internal static string Rule0011SemicolonAfterProcedureDeclarationDescription {
            get {
                return ResourceManager.GetString("Rule0011SemicolonAfterProcedureDeclarationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure must not end with semicolon..
        /// </summary>
        internal static string Rule0011SemicolonAfterProcedureDeclarationFormat {
            get {
                return ResourceManager.GetString("Rule0011SemicolonAfterProcedureDeclarationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure must not end with semicolon..
        /// </summary>
        internal static string Rule0011SemicolonAfterProcedureDeclarationTitle {
            get {
                return ResourceManager.GetString("Rule0011SemicolonAfterProcedureDeclarationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure must be either local or internal..
        /// </summary>
        internal static string Rule0012InternalProceduresDescription {
            get {
                return ResourceManager.GetString("Rule0012InternalProceduresDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure must be either local or internal..
        /// </summary>
        internal static string Rule0012InternalProceduresFormat {
            get {
                return ResourceManager.GetString("Rule0012InternalProceduresFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure must be either local or internal..
        /// </summary>
        internal static string Rule0012InternalProceduresTitle {
            get {
                return ResourceManager.GetString("Rule0012InternalProceduresTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolTip must end with a dot..
        /// </summary>
        internal static string Rule0013ToolTipPunctuationDescription {
            get {
                return ResourceManager.GetString("Rule0013ToolTipPunctuationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolTip must end with a dot..
        /// </summary>
        internal static string Rule0013ToolTipPunctuationFormat {
            get {
                return ResourceManager.GetString("Rule0013ToolTipPunctuationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolTip must end with a dot..
        /// </summary>
        internal static string Rule0013ToolTipPunctuationTitle {
            get {
                return ResourceManager.GetString("Rule0013ToolTipPunctuationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position for global variables, triggers and methods..
        /// </summary>
        internal static string Rule0014GlobalVarTriggerAndMethodPositionDescription {
            get {
                return ResourceManager.GetString("Rule0014GlobalVarTriggerAndMethodPositionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ordering should be like this: Global Variables -&gt; Triggers -&gt; Methods..
        /// </summary>
        internal static string Rule0014GlobalVarTriggerAndMethodPositionFormat {
            get {
                return ResourceManager.GetString("Rule0014GlobalVarTriggerAndMethodPositionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position for global variables, triggers and methods..
        /// </summary>
        internal static string Rule0014GlobalVarTriggerAndMethodPositionTitle {
            get {
                return ResourceManager.GetString("Rule0014GlobalVarTriggerAndMethodPositionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Msg and Err labels should end with a dot, Qst should end with a question mark..
        /// </summary>
        internal static string Rule0015LabelPunctuationDescription {
            get {
                return ResourceManager.GetString("Rule0015LabelPunctuationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Msg and Err labels should end with a dot, Qst should end with a question mark..
        /// </summary>
        internal static string Rule0015LabelPunctuationFormat {
            get {
                return ResourceManager.GetString("Rule0015LabelPunctuationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Msg and Err labels should end with a dot, Qst should end with a question mark..
        /// </summary>
        internal static string Rule0015LabelPunctuationTitle {
            get {
                return ResourceManager.GetString("Rule0015LabelPunctuationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Methods must be invoked with explicit parameters..
        /// </summary>
        internal static string Rule0016InternalMethodsMustHaveExplicitParametersDescription {
            get {
                return ResourceManager.GetString("Rule0016InternalMethodsMustHaveExplicitParametersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Methods must be invoked with explicit parameters..
        /// </summary>
        internal static string Rule0016InternalMethodsMustHaveExplicitParametersFormat {
            get {
                return ResourceManager.GetString("Rule0016InternalMethodsMustHaveExplicitParametersFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Methods must be invoked with explicit parameters..
        /// </summary>
        internal static string Rule0016InternalMethodsMustHaveExplicitParametersTitle {
            get {
                return ResourceManager.GetString("Rule0016InternalMethodsMustHaveExplicitParametersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object should not have empty sections..
        /// </summary>
        internal static string Rule0017EmptyObjectSectionsDescription {
            get {
                return ResourceManager.GetString("Rule0017EmptyObjectSectionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object should not have empty sections..
        /// </summary>
        internal static string Rule0017EmptyObjectSectionsFormat {
            get {
                return ResourceManager.GetString("Rule0017EmptyObjectSectionsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object should not have empty sections..
        /// </summary>
        internal static string Rule0017EmptyObjectSectionsTitle {
            get {
                return ResourceManager.GetString("Rule0017EmptyObjectSectionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects need to have the Access properties defined..
        /// </summary>
        internal static string Rule0018ObjectAccessPropertyDescription {
            get {
                return ResourceManager.GetString("Rule0018ObjectAccessPropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects need to have the Access properties defined..
        /// </summary>
        internal static string Rule0018ObjectAccessPropertyFormat {
            get {
                return ResourceManager.GetString("Rule0018ObjectAccessPropertyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects need to have the Access properties defined..
        /// </summary>
        internal static string Rule0018ObjectAccessPropertyTitle {
            get {
                return ResourceManager.GetString("Rule0018ObjectAccessPropertyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects need to have the Extensible properties defined..
        /// </summary>
        internal static string Rule0018ObjectExtensiblePropertyDescription {
            get {
                return ResourceManager.GetString("Rule0018ObjectExtensiblePropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects need to have the Extensible properties defined..
        /// </summary>
        internal static string Rule0018ObjectExtensiblePropertyFormat {
            get {
                return ResourceManager.GetString("Rule0018ObjectExtensiblePropertyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects need to have the Extensible properties defined..
        /// </summary>
        internal static string Rule0018ObjectExtensiblePropertyTitle {
            get {
                return ResourceManager.GetString("Rule0018ObjectExtensiblePropertyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local variable name should not contain whitespace.
        /// </summary>
        internal static string Rule0019LocalVariableNameShouldNotContainWhiteSpaceDescription {
            get {
                return ResourceManager.GetString("Rule0019LocalVariableNameShouldNotContainWhiteSpaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local variable with name &apos;{0}&apos; must not contain whitespaces..
        /// </summary>
        internal static string Rule0019LocalVariableNameShouldNotContainWhiteSpaceFormat {
            get {
                return ResourceManager.GetString("Rule0019LocalVariableNameShouldNotContainWhiteSpaceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local variable name should not contain whitespace.
        /// </summary>
        internal static string Rule0019LocalVariableNameShouldNotContainWhiteSpaceTitle {
            get {
                return ResourceManager.GetString("Rule0019LocalVariableNameShouldNotContainWhiteSpaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local variable name should not contain wildcard symbols such as % or &amp;.
        /// </summary>
        internal static string Rule0019LocalVariableNameShouldNotContainWildcardSymbolsDescription {
            get {
                return ResourceManager.GetString("Rule0019LocalVariableNameShouldNotContainWildcardSymbolsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local variable with name &apos;{0}&apos; must not contain wildcard symbols..
        /// </summary>
        internal static string Rule0019LocalVariableNameShouldNotContainWildcardSymbolsFormat {
            get {
                return ResourceManager.GetString("Rule0019LocalVariableNameShouldNotContainWildcardSymbolsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local variable name should not contain wildcard symbols such as % or &amp;.
        /// </summary>
        internal static string Rule0019LocalVariableNameShouldNotContainWildcardSymbolsTitle {
            get {
                return ResourceManager.GetString("Rule0019LocalVariableNameShouldNotContainWildcardSymbolsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global variable name should not contain whitespace.
        /// </summary>
        internal static string Rule0020GlobalVariableNameShouldNotContainWhiteSpaceDescription {
            get {
                return ResourceManager.GetString("Rule0020GlobalVariableNameShouldNotContainWhiteSpaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global variable with name &apos;{0}&apos; must not contain whitespaces..
        /// </summary>
        internal static string Rule0020GlobalVariableNameShouldNotContainWhiteSpaceFormat {
            get {
                return ResourceManager.GetString("Rule0020GlobalVariableNameShouldNotContainWhiteSpaceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global variable name should not contain whitespace.
        /// </summary>
        internal static string Rule0020GlobalVariableNameShouldNotContainWhiteSpaceTitle {
            get {
                return ResourceManager.GetString("Rule0020GlobalVariableNameShouldNotContainWhiteSpaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global variable name should not contain wildcard symbols such as % or &amp;.
        /// </summary>
        internal static string Rule0020GlobalVariableNameShouldNotContainWildcardSymbolsDescription {
            get {
                return ResourceManager.GetString("Rule0020GlobalVariableNameShouldNotContainWildcardSymbolsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global variable with name &apos;{0}&apos; must not contain wildcard symbols..
        /// </summary>
        internal static string Rule0020GlobalVariableNameShouldNotContainWildcardSymbolsFormat {
            get {
                return ResourceManager.GetString("Rule0020GlobalVariableNameShouldNotContainWildcardSymbolsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global variable name should not contain wildcard symbols such as % or &amp;.
        /// </summary>
        internal static string Rule0020GlobalVariableNameShouldNotContainWildcardSymbolsTitle {
            get {
                return ResourceManager.GetString("Rule0020GlobalVariableNameShouldNotContainWildcardSymbolsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter with name &apos;{0}&apos; must not contain whitespaces..
        /// </summary>
        internal static string Rule0021ParameterNameShouldNotContainWhiteSpaceDescription {
            get {
                return ResourceManager.GetString("Rule0021ParameterNameShouldNotContainWhiteSpaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter with name &apos;{0}&apos; must not contain whitespaces..
        /// </summary>
        internal static string Rule0021ParameterNameShouldNotContainWhiteSpaceFormat {
            get {
                return ResourceManager.GetString("Rule0021ParameterNameShouldNotContainWhiteSpaceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter with name &apos;{0}&apos; must not contain whitespaces..
        /// </summary>
        internal static string Rule0021ParameterNameShouldNotContainWhiteSpaceTitle {
            get {
                return ResourceManager.GetString("Rule0021ParameterNameShouldNotContainWhiteSpaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter name should not contain wildcard symbols such as % or &amp;.
        /// </summary>
        internal static string Rule0021ParameterNameShouldNotContainWildcardSymbolsDescription {
            get {
                return ResourceManager.GetString("Rule0021ParameterNameShouldNotContainWildcardSymbolsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter with name &apos;{0}&apos; must not contain wildcard symbols..
        /// </summary>
        internal static string Rule0021ParameterNameShouldNotContainWildcardSymbolsFormat {
            get {
                return ResourceManager.GetString("Rule0021ParameterNameShouldNotContainWildcardSymbolsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter name should not contain wildcard symbols such as % or &amp;.
        /// </summary>
        internal static string Rule0021ParameterNameShouldNotContainWildcardSymbolsTitle {
            get {
                return ResourceManager.GetString("Rule0021ParameterNameShouldNotContainWildcardSymbolsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GridLayout property must not have value Rows.
        /// </summary>
        internal static string Rule0022GridLayoutMustNotBeRowsDescription {
            get {
                return ResourceManager.GetString("Rule0022GridLayoutMustNotBeRowsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} property must not have value Rows..
        /// </summary>
        internal static string Rule0022GridLayoutMustNotBeRowsFormat {
            get {
                return ResourceManager.GetString("Rule0022GridLayoutMustNotBeRowsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GridLayout property must not have value Rows.
        /// </summary>
        internal static string Rule0022GridLayoutMustNotBeRowsTitle {
            get {
                return ResourceManager.GetString("Rule0022GridLayoutMustNotBeRowsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifier must have at least one of the mandatory affixes..
        /// </summary>
        internal static string Rule0023MandatoryAffixesDescription {
            get {
                return ResourceManager.GetString("Rule0023MandatoryAffixesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifier &apos;{0}&apos; must have at least one of the mandatory affixes &apos;{1}&apos;..
        /// </summary>
        internal static string Rule0023MandatoryAffixesFormat {
            get {
                return ResourceManager.GetString("Rule0023MandatoryAffixesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifier must have at least one of the mandatory affixes..
        /// </summary>
        internal static string Rule0023MandatoryAffixesTitle {
            get {
                return ResourceManager.GetString("Rule0023MandatoryAffixesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty captions should be locked..
        /// </summary>
        internal static string Rule0024EmptyCaptionLockedDescription {
            get {
                return ResourceManager.GetString("Rule0024EmptyCaptionLockedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty captions should be locked..
        /// </summary>
        internal static string Rule0024EmptyCaptionLockedFormat {
            get {
                return ResourceManager.GetString("Rule0024EmptyCaptionLockedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty captions should be locked..
        /// </summary>
        internal static string Rule0024EmptyCaptionLockedTitle {
            get {
                return ResourceManager.GetString("Rule0024EmptyCaptionLockedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetAutoCalcFields must not be invoked on Normal fields..
        /// </summary>
        internal static string Rule0025CalcFieldsOnNormalFieldsDescription {
            get {
                return ResourceManager.GetString("Rule0025CalcFieldsOnNormalFieldsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetAutoCalcFields must not be invoked on Normal fields..
        /// </summary>
        internal static string Rule0025CalcFieldsOnNormalFieldsFormat {
            get {
                return ResourceManager.GetString("Rule0025CalcFieldsOnNormalFieldsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetAutoCalcFields must not be invoked on Normal fields..
        /// </summary>
        internal static string Rule0025CalcFieldsOnNormalFieldsTitle {
            get {
                return ResourceManager.GetString("Rule0025CalcFieldsOnNormalFieldsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero (0) Enum value should be reserved for Empty Value..
        /// </summary>
        internal static string Rule0026ZeroEnumValueReservedForEmptyDescription {
            get {
                return ResourceManager.GetString("Rule0026ZeroEnumValueReservedForEmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero (0) Enum value should be reserved for Empty Value..
        /// </summary>
        internal static string Rule0026ZeroEnumValueReservedForEmptyFormat {
            get {
                return ResourceManager.GetString("Rule0026ZeroEnumValueReservedForEmptyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero (0) Enum value should be reserved for Empty Value..
        /// </summary>
        internal static string Rule0026ZeroEnumValueReservedForEmptyTitle {
            get {
                return ResourceManager.GetString("Rule0026ZeroEnumValueReservedForEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicting ID, Name or Type with Table &apos;{0}&apos;.
        /// </summary>
        internal static string Rule0027AnalyzeTableExtensionText {
            get {
                return ResourceManager.GetString("Rule0027AnalyzeTableExtensionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records &apos;{0}&apos; and &apos;{1}&apos; have conflicting fields with the same ID.
        /// </summary>
        internal static string Rule0027AnalyzeTransferFieldText {
            get {
                return ResourceManager.GetString("Rule0027AnalyzeTransferFieldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze &apos;Get&apos; function call arguments..
        /// </summary>
        internal static string Rule0028_1IncorrectArgumentCountDescription {
            get {
                return ResourceManager.GetString("Rule0028_1IncorrectArgumentCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Get&apos; function call on table &apos;{0}&apos; should have {1} argument(s)..
        /// </summary>
        internal static string Rule0028_1IncorrectArgumentCountFormat {
            get {
                return ResourceManager.GetString("Rule0028_1IncorrectArgumentCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of arguments in &apos;Get&apos; function call.
        /// </summary>
        internal static string Rule0028_1IncorrectArgumentCountTitle {
            get {
                return ResourceManager.GetString("Rule0028_1IncorrectArgumentCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze &apos;Get&apos; function call argument types..
        /// </summary>
        internal static string Rule0028_2InvalidArgumentTypeInGetCallDescription {
            get {
                return ResourceManager.GetString("Rule0028_2InvalidArgumentTypeInGetCallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument in &apos;Get&apos; function call on table &apos;{0}&apos; has incorrect type..
        /// </summary>
        internal static string Rule0028_2InvalidArgumentTypeInGetCallFormat {
            get {
                return ResourceManager.GetString("Rule0028_2InvalidArgumentTypeInGetCallFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument type in &apos;Get&apos; function call.
        /// </summary>
        internal static string Rule0028_2InvalidArgumentTypeInGetCallTitle {
            get {
                return ResourceManager.GetString("Rule0028_2InvalidArgumentTypeInGetCallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze &apos;Get&apos; function call argument lengths..
        /// </summary>
        internal static string Rule0028_3ArgumentLengthExceedsMaxLengthDescription {
            get {
                return ResourceManager.GetString("Rule0028_3ArgumentLengthExceedsMaxLengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument length in &apos;Get&apos; function call on table &apos;{0}&apos; should not exceed the maximum length of &apos;{1}&apos;..
        /// </summary>
        internal static string Rule0028_3ArgumentLengthExceedsMaxLengthFormat {
            get {
                return ResourceManager.GetString("Rule0028_3ArgumentLengthExceedsMaxLengthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument length exceeds field maximum length in &apos;Get&apos; function call.
        /// </summary>
        internal static string Rule0028_3ArgumentLengthExceedsMaxLengthTitle {
            get {
                return ResourceManager.GetString("Rule0028_3ArgumentLengthExceedsMaxLengthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This rule throws a warning when an Option data type is used, as it is not allowed..
        /// </summary>
        internal static string Rule0029OptionDataTypeNotAllowedDescription {
            get {
                return ResourceManager.GetString("Rule0029OptionDataTypeNotAllowedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option data type is not allowed in the code..
        /// </summary>
        internal static string Rule0029OptionDataTypeNotAllowedFormat {
            get {
                return ResourceManager.GetString("Rule0029OptionDataTypeNotAllowedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option data type Not Allowed.
        /// </summary>
        internal static string Rule0029OptionDataTypeNotAllowedTitle {
            get {
                return ResourceManager.GetString("Rule0029OptionDataTypeNotAllowedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redundant editable properties can clutter code and lead to confusion..
        /// </summary>
        internal static string Rule0033RedundantEditablePropertyDescription {
            get {
                return ResourceManager.GetString("Rule0033RedundantEditablePropertyDescription", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to Changing &apos;Editable&apos; property of a field when the base object field is set to a global variable throws an error while publishing..
        /// </summary>
        internal static string Rule0034PageExtensionEditableFieldDescription
        {
            get
            {
                return ResourceManager.GetString("Rule0034PageExtensionEditableFieldDescription", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to Unused global procedures can contribute to unnecessary code clutter..
        /// </summary>
        internal static string Rule0035UnusedGlobalProcedureDescription {
            get {
                return ResourceManager.GetString("Rule0035UnusedGlobalProcedureDescription", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to Unused objects can lead to unnecessary clutter in the codebase..
        /// </summary>
        internal static string Rule0031ObjectIsUnusedDescription {
            get {
                return ResourceManager.GetString("Rule0031ObjectIsUnusedDescription", resourceCulture);
        ///   Looks up a localized string similar to Unused method parameters can clutter code and make it harder to understand..
        /// </summary>
            }
        }
        internal static string Rule0030UnusedMethodParametersDescription {
            get {
                return ResourceManager.GetString("Rule0030UnusedMethodParametersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Editable&apos; Property is Redundant Due to the Presence of Object-Level Editable Property Being Defined as False..
        /// </summary>
        internal static string Rule0033RedundantEditablePropertyFormat {
            get {
                return ResourceManager.GetString("Rule0033RedundantEditablePropertyFormat", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to The &apos;Editable&apos; property of the base object field &apos;{0}&apos; is set to a global variable. This will throw an error when publishing..
        /// </summary>
        internal static string Rule0034PageExtensionEditableFieldFormat
        {
            get
            {
                return ResourceManager.GetString("Rule0034PageExtensionEditableFieldFormat", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to The global procedure &apos;{0}&apos; is defined but not used..
        /// </summary>
        internal static string Rule0035UnusedGlobalProcedureFormat {
            get {
                return ResourceManager.GetString("Rule0035UnusedGlobalProcedureFormat", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to The {0} &apos;{1}&apos; is declared but not used..
        /// </summary>
        internal static string Rule0031ObjectIsUnusedFormat {
            get {
                return ResourceManager.GetString("Rule0031ObjectIsUnusedFormat", resourceCulture);
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; is unused in &apos;{1}&apos;.
        /// </summary>
            }
        }
        internal static string Rule0030UnusedMethodParametersFormat {
            get {
                return ResourceManager.GetString("Rule0030UnusedMethodParametersFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redundant Editable Property.
        /// </summary>
        internal static string Rule0033RedundantEditablePropertyTitle {
            get {
                return ResourceManager.GetString("Rule0033RedundantEditablePropertyTitle", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to Invalid Page Extension Editable Field Property.
        /// </summary>
        internal static string Rule0034PageExtensionEditableFieldTitle
        {
            get
            {
                return ResourceManager.GetString("Rule0034PageExtensionEditableFieldTitle", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to Unused Global Procedure.
        /// </summary>
        internal static string Rule0035UnusedGlobalProcedureTitle {
            get {
                return ResourceManager.GetString("Rule0035UnusedGlobalProcedureTitle", resourceCulture);
            }
        }
        ///   Looks up a localized string similar to Unused Object.
        /// </summary>
        internal static string Rule0031ObjectIsUnusedTitle {
            get {
                return ResourceManager.GetString("Rule0031ObjectIsUnusedTitle", resourceCulture);
        ///   Looks up a localized string similar to Unused Method Parameters.
        /// </summary>
            }
        }
        internal static string Rule0030UnusedMethodParametersTitle {
            get {
                return ResourceManager.GetString("Rule0030UnusedMethodParametersTitle", resourceCulture);
            }
        }
    }
}
